1 CLS :PRINT "Drums test 1995 K.Motoi"
2 PLAY "T5"
3 A=INT (RND 8)+3:GOTO A
4 *A1:GOSUB *B:GOSUB *H:GOSUB *H:GOSUB *H:GOTO 3
5 *A2:GOSUB *S:GOSUB *H:GOSUB *B:GOSUB *H:GOTO 3
6 *A3:GOSUB *B:GOSUB *H:GOSUB *S:GOSUB *B:GOTO 3
7 *A4:GOSUB *B:GOSUB *S:GOSUB *H:GOSUB *S:GOTO 3
8 *A5:GOSUB *B:GOSUB *H:GOSUB *B:GOSUB *H:GOTO 3
9 *A6:GOSUB *S:GOSUB *S:GOSUB *B:GOSUB *S:GOTO 3
10 *A7:GOSUB *B:GOSUB *S:GOSUB *S:GOSUB *H:GOTO 3
11 *A8:GOSUB *B:GOSUB *B:GOSUB *H:GOSUB *S:GOTO 3
13 '*S:PLAY "L1O3BAGFEDC<BAGFEDC<BR:O2L2BAGFEDC<BAGFEDC<BR:O0L2FFFFCCCCCCCCRRRR":RETURN
14 *S:PLAY "L1O3BAGFEDC<BAGFEDC<BR:O2L2BAGFEDC<BAGFEDC<BR:O1L0R3FGABDCFE":RETURN F
15 *B:PLAY "L1O1BAGFEDC<BAGFEDCRR:L1O1BAGFEDCR:L1O2BAGFEDCR":RETURN
16 *H:PLAY "L1O0BRCRBRCRBCRRBRCR:L1O1BRRRRRRR:L1O2BRRRRRRR":RETURN
17 *R:PLAY "R9R5":RETURN

